### PR TITLE
refactoring, responsiveness, documentation…

### PR DESCRIPTION
**Pull request by tippi-fifestarr**
Components, responsiveness in midpage, using next/Image

- [x]  Rename CreateHeader to CreateHero
- [x]  Replace img tags with [[Next Image](https://nextjs.org/docs/api-reference/next/image)](https://nextjs.org/docs/api-reference/next/image)
    - [x]  [https://nextjs.org/docs/basic-features/image-optimization#using-the-image-component](https://nextjs.org/docs/basic-features/image-optimization#using-the-image-component)
- [x]  Make navbar into a component
- [x]  Make navbar responsive
    - [x]  hamburger menu has functionality
- [x]  Make “try now” button into a responsive component
- [x]  Center and align text and icons in the feature sections to display one at a time on small screens
- [x]  Improve documentation

### CODE REVIEW

**Comment by tippi-fifestarr** [comment]
Completed UI update except for [one specific thing](https://github.com/DnDnDiffusion/Front-end/blob/b4c312acfa42cbfedf4266478b4ecdfe89ae73d2/components/CreateMidpage.jsx#L83)

**Comment by danj-O** [comment]
Issues:
- "try Now" button is fixed on screen, it should static inside the header. also, i think the whole hero is now a link which feels weird.
- logo too large
- navbar links hover scaling text moves all other text around it.  doesn't need to scale, just color change
- navbar links should be positioned right further
- responsive hamburgers works! but it's not finished yet. still need the dropdown in mobile. consider the switch at md: instead of sm: so navlinks don't overlap
- the tooltips idea is ok, but we already guide them with visuals and text through the process. also, i'm not sure the toggle does anything yet?
- half of the details boxes are now responsive! the second row is not.

**Comment by tippi-fifestarr** [comment]
@danj-O I deleted the navbar text size hoverupdates and resized the logo smaller.

**Comment by tippi-fifestarr** [comment]
https://youtu.be/zX3cSHaGO5s @danj-O @carteblanchecarriage

**Comment by tippi-fifestarr** [comment]
@danj-O are we waiting for some more features to merge this branch?  I'm basing the NFT branch off of design-updates

**Comment by danj-O** [comment]
yeah, the toggle stuff, it looks a bit messy like it is. I think there are still some people working off this as well?

**Comment by tippi-fifestarr** [comment]
Yeah it looks like both Alex and Ali switched focus to separately integrate
Wallet Connect, which makes sense because they both love web3 stuff and
this is a key step for frontends to have haha. I'll try to get us to sync
and finish it today and make sure someone is still on the tooltips so we
can merge this in.

**Comment by danj-O** [comment]
or just remove it for now

**Comment by tippi-fifestarr** [comment]
@0xAli0x how is the progress on the tooltips going?

**Comment by 0xAli0x** [comment]
Yes got it working!

**Comment by tippi-fifestarr** [comment]
@***@***.*** ***@***.***>
Ali did a tooltips!!!!11!!!

**Pull request merged**
